# Generated by Django 6.0.3 on 2026-03-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('service_line', models.CharField(max_length=120)),
                ('bed_capacity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OperationalSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('detail', models.TextField()),
                ('source', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('watch', 'Watch'), ('critical', 'Critical')], default='info', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('acknowledged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(max_length=120)),
                ('license_id', models.CharField(max_length=80)),
                ('languages', models.CharField(max_length=200)),
                ('consultation_modes', models.CharField(max_length=120)),
                ('response_sla_hours', models.PositiveIntegerField(default=4)),
                ('next_opening', models.DateTimeField()),
                ('status', models.CharField(choices=[('online', 'Online'), ('rounding', 'Rounding'), ('offline', 'Offline')], default='online', max_length=20)),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinicians', to='operations.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=120)),
                ('channel', models.CharField(max_length=80)),
                ('concern', models.CharField(max_length=200)),
                ('recommended_pathway', models.CharField(max_length=120)),
                ('severity', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent')], default='routine', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('review', 'In Review'), ('scheduled', 'Scheduled'), ('declined', 'Declined')], default='new', max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('assigned_clinician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_requests', to='operations.clinician')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('patient_code', models.CharField(max_length=20, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=120)),
                ('primary_condition', models.CharField(max_length=160)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('device_readiness', models.CharField(choices=[('ready', 'Ready'), ('assisted', 'Assisted'), ('offline', 'Offline')], default='ready', max_length=20)),
                ('preferred_language', models.CharField(max_length=80)),
                ('adherence_score', models.PositiveIntegerField(default=0)),
                ('last_vitals_at', models.DateTimeField()),
                ('summary', models.TextField()),
                ('clinic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='operations.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('visit_mode', models.CharField(choices=[('video', 'Video'), ('async', 'Async'), ('field', 'Field')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('triage', 'Triage'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('follow_up', 'Follow-up'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('queue_label', models.CharField(max_length=80)),
                ('briefing', models.TextField()),
                ('clinician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='operations.clinician')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='operations.patient')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('ops', 'Operations'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinician',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinician', to='operations.userprofile'),
        ),
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('blocked', 'Blocked'), ('done', 'Done')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('related_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.patient')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='operations.userprofile')),
            ],
        ),
    ]
